### ISSUE TITLE
spawn is not defined

### ISSUE THREAD

**Issue by accateo** [aheckmann/node-email#30]
Whats the reason for

`Uncaught TypeError: spawn is not a function`

error?
Thanks

**Comment by fparedlo** [comment]
Same here

` const lib = require('../../node_modules/email')
  const Email = lib.Email
 
        var mail = new Email({
            from: 'test@yopmail.com',
            to: this.email,
            subject: 'title',
            body: 'body
 })
 mail.send()`

**Comment by Satish-yadav01** [comment]
Error: spawn sendmail ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[nodemon] app crashed - waiting for file changes before starting...


I get this error after using email module can anyone knows this

**Comment by aheckmann** [comment]
Closing. This project is no longer maintained.
